CREATE TABLE sproduct(
	num NUMBER PRIMARY KEY,
	name VARCHAR2(30) NOT NULL,
	price NUMBER NOT NULL,
	stock NUMBER NOT NULL,
	origin VARCHAR2(30) NOT NULL,
	content CLOB NOT NULL,
	reg_date DATE DEFAULT SYSDATE NOT NULL
);

CREATE SEQUENCE sproduct_seq;