CREATE TABLE tboard(
	num NUMBER NOT NULL PRIMARY KEY,
	name VARCHAR2(30) NOT NULL,
	title VARCHAR2(150) NOT NULL,
	passwd VARCHAR2(10) NOT NULL,
	content VARCHAR2(4000) NOT NULL,
	reg_date DATE NOT NULL
);

CREATE SEQUENCE tboard_seq;