CREATE TABLE smember(
	num NUMBER PRIMARY KEY,
	id VARCHAR2(12) UNIQUE NOT NULL,
	name VARCHAR2(30) NOT NULL,
	passwd VARCHAR2(12) NOT NULL,
	email VARCHAR2(50) NOT NULL,
	phone VARCHAR2(15),
	reg_date DATE NOT NULL
);

CREATE SEQUENCE smember_seq;