title: Study Web Development
owner_name: JeongHoon Min
markdown: GFM
# remote_theme: marella/jekyll-theme-documentation
# remote_theme: pmarsceill/just-the-docs
# toc_min: 2
# toc_max: 4
# kramdown:
  # input: GFM
