CREATE TABLE sboard(
	num NUMBER PRIMARY KEY,
	title VARCHAR2(150) NOT NULL,
	name VARCHAR2(30) NOT NULL,
	passwd VARCHAR2(12) NOT NULL,
	content CLOB NOT NULL,
	ip VARCHAR2(30) NOT NULL,
	reg_date DATE NOT NULL
);

CREATE SEQUENCE sboard_seq;